### ISSUE TITLE
Certificado HTTPS caduco

### ISSUE THREAD

**Issue by IkerGimenez** [soydetemporada/website#17]
Buenas,
No sé si esto va en su proyecto de backend, pero el certificado HTTPS a través de Let's Encrypt ha expirado y no se ha renovado. Si les puedo ayudar porque no tienen tiempo, con gusto lo investigo y hago un Pull Request.
Gracias de antemano.

**Comment by ffosset** [comment]
Muchas gracias por tu mensaje Iker, justo @lowfill lo está gestionando ahora. Te agradecemos la ayuda 😊

**Comment by lowfill** [comment]
Hola @IkerGimenez muchas gracias por reportar el problema. Ya ha sido solucionado.

**Comment by IkerGimenez** [comment]
Fabuloso, muchísimas gracias

**Comment by IkerGimenez** [comment]
Perdón por la molestia, pero ha vuelto a caducar el certificado. Si se puede ayudar con algo, con gusto colaboro. Gracias!

**Comment by ffosset** [comment]
Hola Iker, ¡que gusto ver que gente sigue utilizando la plataforma! Gracias por avisarnos, @lowfill debería poder arreglarlo pronto.

**Comment by lowfill** [comment]
@IkerGimenez gracias por avisarnos. Se nos había pasado el renovarlo. Ya esta renovado.

**Comment by IkerGimenez** [comment]
Muchas gracias a ustedes por mantener el sitio activo, lo uso siempre que planeo la compra para la semana. Saludos!
