### ISSUE TITLE
https

### ISSUE THREAD

**Issue by flowsta** [soydetemporada/website#3]
Como ocurre con todo proyecto web que se aloja en github, no dispone de la posibilidad de incluir un certificado para el dominio propio... ¿Podríais pasar a un alojamiento propio? Así dispondríais de https, por ejemplo.

**Comment by lowfill** [comment]
Github habilitó la posibilidad de usar Let's Encrypt en páginas con nombres personalizados. Estamos haciendo uso de esa opción.
