### ISSUE TITLE
Add section "en los medios"

### ISSUE THREAD

**Issue by ffosset** [soydetemporada/website#9]
Añadir una sección que recopila los enlaces a los artículos que hablan del proyecto.

- [Premio Xataka Live Citizen](https://www.xataka.com/xataka/mejor-proyecto-xataka-live-citizen-participa-en-los-premios-xataka-2017)
- [Noticias Positivas](http://noticiaspositivas.org/espana/calendario-colaborativo-verduras-frutas/)
- [Mumumío](http://blog.mumumio.com/post/2017/10/23/flora-fosset-%F0%9F%8D%93%F0%9F%8D%87%F0%9F%8D%8B%F0%9F%8D%88%F0%9F%8D%85%F0%9F%8D%86%F0%9F%8D%8A%F0%9F%8D%8F/)
- [Gastronomía&Cía](https://gastronomiaycia.republica.com/2017/10/27/recuperar-el-calendario-de-productos-de-temporada/)
- [Diario de Gastronomia](http://diariodegastronomia.com/calendario-colaborativo-frutas-verduras-temporada-espana/)
- Revista Soberanía Alimentaria
- El Comidista

**Comment by ffosset** [comment]
- [El País Buena Vida](https://elpais.com/elpais/2018/03/07/buenavida/1520440308_049503.html)
- Eurofresh Distribution Magazine

**Comment by ffosset** [comment]
Radio M-21 - [Einstein en Malasaña](https://www.m21radio.es/podcast/einstein-en-malasana/einstein-en-malasana-13122017)

**Comment by lowfill** [comment]
Closed in ed4e8d9 

Added _data/press.csv to manage this
